### ISSUE TITLE
$this->queue = \yii\di\Instance::ensure($this->queue,Queue::className()) errors

### ISSUE THREAD

**Issue by gorgle** [urbanindo/yii2-queue#47]
I create a new QueueController extends yii\console\Controller like you ,it's report errors when I execute the commands " php yii ",these errors like :Stack trace:
#0 /www/mcolor/application/vendor/yiisoft/yii2/di/Container.php(422): ReflectionClass->__construct('queue')
#1 /www/mcolor/application/vendor/yiisoft/yii2/di/Container.php(362): yii\di\Container->getDependencies('queue')
#2 /www/mcolor/application/vendor/yiisoft/yii2/di/Container.php(154): yii\di\Container->build('queue', Array, Array)
#3 /www/mcolor/application/vendor/yiisoft/yii2/di/Instance.php(154): yii\di\Container->get('queue')
#4 /www/mcolor/application/vendor/yiisoft/yii2/di/Instance.php(128): yii\di\Instance->get(NULL)
#5 /www/mcolor/application/commands/QueueController.php(41): yii\di\Instance::ensure(Object(yii\di\Instance), 'UrbanIndo\\Yii2\\...')
#6 /www/mcolor/application/vendor/yiisoft/yii2/base/Object.php(107): app\commands\QueueController->init()
#7 /www/mcolor/application/vendor/yiisoft/yii2/base/Controller.php(84): yii\base\Object->__construct(Array)
#8 [internal function]: yii\base\Controller->__construct('queue', Object(yii\console\Application), Array)
#9 /www/mcolor/application/vendor/yiisoft/yii2/di/Container.php(373): ReflectionClass->newInstanceArgs(Array)
#10 /www/mcolor/application/vendor/yiisoft/yii2/di/Container.php(154): yii\di\Container->build('app\\commands\\Qu...', Array, Array)
#11 /www/mcolor/application/vendor/yiisoft/yii2/BaseYii.php(340): yii\di\Container->get('app\\commands\\Qu...', Array)
#12 /www/mcolor/application/vendor/yiisoft/yii2/base/Module.php(567): yii\BaseYii::createObject('app\\commands\\Qu...', Array)
#13 /www/mcolor/application/vendor/yiisoft/yii2/base/Module.php(520): yii\base\Module->createControllerByID('queue')
#14 /www/mcolor/application/vendor/yiisoft/yii2/console/controllers/HelpController.php(92): yii\base\Module->createController('')
#15 /www/mcolor/application/vendor/yiisoft/yii2/console/controllers/HelpController.php(184): yii\console\controllers\HelpController->getCommandDescriptions()
#16 /www/mcolor/application/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#17 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#18 /www/mcolor/application/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#19 /www/mcolor/application/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#20 /www/mcolor/application/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('', Array)
#21 /www/mcolor/application/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('', Array)
#22 /www/mcolor/application/vendor/yiisoft/yii2/console/Application.php(176): yii\base\Module->runAction('', Array)
#23 /www/mcolor/application/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('', Array)
#24 /www/mcolor/application/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#25 /www/mcolor/application/yii(22): yii\base\Application->run()
#26 {main}

I'm a new phper ,plz tell me why the \yii\di\Instance::ensure report errors;

**Comment by gorgle** [comment]
completed! sorry
